---
- name: Deploy EpicBook Application on AWS EC2 Instance
  hosts: app
  become: true
  vars_files:
    - ../vars/env.yml
    - ../vars/vault.yml
    - ../vars/rds.yml

  roles:
    - app
    - rds
    # - database
    - epicbook
    - nginx
