---
- name: Install and Configure Nginx Server
  hosts: app
  become: true
  tasks:
    - name: Ensure apt cache is updated
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 3600

    - name: Install Nginx
      ansible.builtin.apt:
        name: nginx
        state: present

    - name: Ensure Nginx service is enabled and running
      ansible.builtin.service:
        name: nginx
        state: started
        enabled: true

- name: Deploy Mini Finance Project
  hosts: app
  become: true
  vars:
    project_repo: "https://github.com/imShakil/mini_finance"
    project_src: "/tmp/mini_finance"
    nginx_root: "/var/www/html"

  tasks:
    - name: Remove Old files
      ansible.builtin.file:
        path: "{{ project_src }}"
        state: absent

    - name: Clone Mini Finance Project
      ansible.builtin.git:
        repo: "{{ project_repo }}"
        dest: "{{ project_src }}"
        version: 'main'

    - name: Sync project files to Nginx root
      ansible.builtin.copy:
        src: "{{ project_src }}/"
        dest: "{{ nginx_root }}/"
        owner: www-data
        group: www-data
        mode: '0755'
        remote_src: true

    - name: Restart Nginx to apply changes
      ansible.builtin.service:
        name: nginx
        state: restarted

- name: Test Deployment
  hosts: all
  become: true
  tasks:
    - name: Debug ansible_nodename
      ansible.builtin.debug:
        msg: "Hostname is: {{ inventory_hostname }}"
    - name: Test locally
      ansible.builtin.uri:
        url: http://127.0.0.1
        return_content: true
    - name: Test public Access
      ansible.builtin.uri:
        url: "http://{{ inventory_hostname }}"
        return_content: true
